/**
 * Annotation plugin stylesheet, injected as one <style data-plugin> tag at
 * apply time. Everything follows the dsh standard style system: pill geometry
 * for the composer chip, menu-card language for the popover, the design
 * platform's floating-control pair for the add button, standard interactive
 * hover tokens, and the deepseek blue family for the annotation identity.
 */

import { BLUE, BLUE_SOFT, HIGHLIGHT } from './theme.ts'

/** Plugin id stamped onto the injected style tag (the loader sweeps these on unload). */
export const PLUGIN_ID = '@neplich/dsh-annotations'

/** The full stylesheet text. */
export const STYLE_TEXT = [
  // Highlight: pure background over the message text — no padding, inherited
  // color, so annotated messages keep their exact layout and typography.
  `mark[data-dsh-annot] {`,
  `  background: color-mix(in srgb, ${HIGHLIGHT} 26%, transparent);`,
  '  color: inherit;',
  '  border-radius: 2px;',
  '  box-decoration-break: clone;',
  '  -webkit-box-decoration-break: clone;',
  '}',
  'mark[data-dsh-annot].dsh-annot-active {',
  `  background: color-mix(in srgb, ${HIGHLIGHT} 44%, transparent);`,
  '}',
  'mark[data-dsh-annot].dsh-annot-flash {',
  '  animation: dsh-annot-flash 1.2s ease-out;',
  '}',
  '@keyframes dsh-annot-flash {',
  `  0% { box-shadow: 0 0 0 0 color-mix(in srgb, ${BLUE_SOFT} 70%, transparent); }`,
  `  30% { box-shadow: 0 0 0 4px color-mix(in srgb, ${BLUE_SOFT} 50%, transparent); }`,
  '  100% { box-shadow: 0 0 0 0 transparent; }',
  '}',
  'body[data-ds-dark-theme] mark[data-dsh-annot] {',
  `  background: color-mix(in srgb, ${HIGHLIGHT} 30%, transparent);`,
  '}',
  'body[data-ds-dark-theme] mark[data-dsh-annot].dsh-annot-active {',
  `  background: color-mix(in srgb, ${HIGHLIGHT} 48%, transparent);`,
  '}',
  // Floating add button: the design platform's standard floating-control
  // pair — both opaque solids, so hovering only shifts the tone.
  '.dsh-annot-add {',
  '  pointer-events: auto;',
  '  position: fixed;',
  '  z-index: 2147483000;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  gap: 6px;',
  '  height: 30px;',
  '  padding: 0 12px;',
  '  border: 1px solid var(--dsw-alias-border-inverted);',
  '  border-radius: 15px;',
  '  background: var(--dsw-alias-button-floating-fill);',
  '  box-shadow: var(--dsw-shadow-lv2);',
  '  font-size: 13px;',
  '  line-height: 20px;',
  '  font-weight: 500;',
  '  color: var(--dsw-alias-label-primary);',
  '  cursor: pointer;',
  '}',
  '.dsh-annot-add:hover, .dsh-annot-add:active {',
  '  background: var(--dsw-alias-button-floating-hover);',
  '}',
  // Composer chip: standard Pill geometry, tinted with the annotation blue.
  '.dsh-annot-chipwrap {',
  '  display: inline-flex;',
  '  align-items: center;',
  '}',
  '.dsh-annot-chip {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 2px;',
  '  height: 24px;',
  '  padding: 0 3px 0 6px;',
  '  border-radius: 12px;',
  `  background: color-mix(in srgb, ${BLUE} 15%, transparent);`,
  `  border: 1px solid color-mix(in srgb, ${BLUE} 32%, transparent);`,
  '}',
  '.dsh-annot-chip:hover {',
  `  border-color: color-mix(in srgb, ${BLUE} 55%, transparent);`,
  '}',
  '.dsh-annot-chiptoggle {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 4px;',
  '  height: 100%;',
  '  padding: 0 4px;',
  '  border: none;',
  '  background: transparent;',
  '  border-radius: 10px;',
  '  cursor: pointer;',
  '  font-size: 12px;',
  '  line-height: 18px;',
  '  color: var(--dsw-alias-label-primary);',
  '}',
  '.dsh-annot-chiptoggle:hover, .dsh-annot-chiptoggle:focus-visible {',
  '  background: var(--dsw-alias-interactive-bg-hover);',
  '  outline: none;',
  '}',
  '.dsh-annot-chipclear {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  flex: none;',
  '  width: 18px;',
  '  height: 18px;',
  '  border: none;',
  '  border-radius: 9px;',
  '  background: transparent;',
  '  cursor: pointer;',
  '  font-size: 12px;',
  '  line-height: 1;',
  '  padding: 0;',
  '  color: var(--dsw-alias-label-secondary);',
  '}',
  '.dsh-annot-chipclear:hover {',
  '  color: var(--dsw-alias-label-primary);',
  '  background: var(--dsw-alias-interactive-bg-hover);',
  '}',
  // Popover: menu-card surface with dense menu cells; each entry is one row
  // (number, the selected text, the delete button).
  '.dsh-annot-popover {',
  '  pointer-events: auto;',
  '  position: fixed;',
  '  z-index: 2147483000;',
  '  box-sizing: border-box;',
  '  min-width: 240px;',
  '  max-height: 380px;',
  '  overflow-y: auto;',
  '  padding: 4px;',
  '  border: 1px solid var(--dsw-alias-border-inverted);',
  '  border-radius: 12px;',
  '  background: var(--dsw-specific-menu);',
  '  box-shadow: var(--dsw-shadow-lv3);',
  '  --dsh-scrollbar-thumb: var(--dsw-alias-scrollbar-bg-l2);',
  '  --dsh-scrollbar-thumb-hover: var(--dsw-alias-scrollbar-hover-l2);',
  '}',
  '.dsh-annot-item {',
  '  display: flex;',
  '  align-items: flex-start;',
  '  gap: 8px;',
  '  border-radius: 10px;',
  '  padding: 6px 8px;',
  '}',
  '.dsh-annot-item + .dsh-annot-item {',
  '  border-top: 1px solid var(--dsw-alias-border-l1);',
  '  margin-top: 2px;',
  '  padding-top: 8px;',
  '}',
  '.dsh-annot-index {',
  '  flex: none;',
  '  font-size: 12px;',
  '  line-height: 20px;',
  '  font-weight: 500;',
  `  color: ${BLUE};`,
  '}',
  '.dsh-annot-text {',
  '  flex: 1;',
  '  min-width: 0;',
  '  font-size: 13px;',
  '  line-height: 20px;',
  '  color: var(--dsw-alias-label-primary);',
  '  white-space: pre-wrap;',
  '  word-break: break-word;',
  '  max-height: 160px;',
  '  overflow-y: auto;',
  '  cursor: pointer;',
  '  border-radius: 6px;',
  '  padding: 0 4px;',
  '  margin: 0 -4px;',
  '}',
  '.dsh-annot-text:hover, .dsh-annot-text:focus-visible {',
  '  background: var(--dsw-alias-interactive-bg-hover);',
  '  outline: none;',
  '}',
  '.dsh-annot-itemdel {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  flex: none;',
  '  width: 22px;',
  '  height: 22px;',
  '  border: none;',
  '  border-radius: 11px;',
  '  background: transparent;',
  '  cursor: pointer;',
  '  font-size: 12px;',
  '  line-height: 1;',
  '  padding: 0;',
  '  color: var(--dsw-alias-label-tertiary);',
  '}',
  '.dsh-annot-itemdel:hover {',
  '  color: var(--dsw-alias-label-primary);',
  '  background: var(--dsw-alias-interactive-bg-hover);',
  '}',
].join('\n')
